### ISSUE TITLE
Please post your Whitepaper in epub and / or mobi

### ISSUE THREAD

**Issue by ddaws** [stx-technologies/stox-token#2]
This would be greatly appreciated!

**Comment by lbeder** [comment]
Hi,

At the moment, the white paper is available in PDF format here:
- English: https://www.stox.com/assets/stox-whitepaper.pdf
- Russian; https://www.stox.com/assets/stox-whitepaper-ru.pdf
- Simplified Chinese: https://www.stox.com/assets/stox-whitepaper-zh.pdf

Since the team is now working 24/7 on delivering the product, I believe it'll take some time to get to this. Noted, and closing for now.

**Comment by ddaws** [comment]
How about posting the source for the paper (Word, Markdown, LaTex or whatever it might be) and I will generate the epub and mobi formats for you and submit them?

**Comment by lbeder** [comment]
Why do you need this, BTW?

**Comment by nsomaru** [comment]
to read on kindle.
